apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "my-backend.fullname" . }}
  labels:
    {{- include "my-backend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "my-backend.fullname" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "my-backend.fullname" . }}
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - containerPort: 5000
