apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-backend.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "my-backend.fullname" . }}
  ports:
    - name: backend
      port: {{ .Values.service.backendPort }}
      targetPort: 5000
